name: audio_manager
description: A flutter plugin for music playback, including notification handling.
version: 0.3.1+1
homepage: https://github.com/jeromexiong/audio_manager

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: cc.dync.audio_manager
        pluginClass: AudioManagerPlugin
      ios:
        pluginClass: AudioManagerPlugin
